<h2>Load some RDF</h2>
<form action="/sparql/load">
    <input type="text" name="url" />
    <input type="submit" value="Load" />
</form>

<h2>See all Data</h2>
<p><a href="/sparql/raw">Raw</a> view</p>

<h2>Do a query</h2>
<form action="/sparql/query">
    <textarea name="query" rows="40" cols="80">
<?php print $this->escape('PREFIX app: <http://www.radarnetworks.com/shazam#> .
PREFIX basic: <http://www.radarnetworks.com/2007/09/12/basic#> .
PREFIX bio: <http://purl.org/vocab/bio/0.1/> .
PREFIX dataview: <http://www.w3.org/2003/g/data-view#> .
PREFIX dc: <http://purl.org/dc/elements/1.1/> .
PREFIX foaf: <http://xmlns.com/foaf/0.1/> .
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .
PREFIX h: <http://www.w3.org/1999/xhtml> .
PREFIX lfm: <http://purl.org/ontology/last-fm/> .
PREFIX mail: <http://www.radarnetworks.com/shazam/mail#> .
PREFIX mo: <http://purl.org/ontology/mo/> .
PREFIX ns0: <http://gmpg.org/xfn/11#> .
PREFIX owl: <http://www.w3.org/2002/07/owl#> .
PREFIX radar: <http://www.radarnetworks.com/core#> .
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
PREFIX web: <http://www.radarnetworks.com/web#> .
PREFIX xml: <http://www.w3.org/XML/1998/namespace> .
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> .
PREFIX ya: <http://blogs.yandex.ru/schema/foaf/> .

SELECT ?person ?name ?location ?lat ?long ?area
        WHERE {
            ?person a foaf:Person .
            ?person foaf:based_near ?location .
            ?person foaf:name ?name .

            OPTIONAL {
                ?location geo:lat ?lat .
                ?location geo:lat ?long .
            }
            OPTIONAL {
                ?location a geo:SpatialThing .
                ?location foaf:name ?area .
            }
        } LIMIT 3'); ?>
    </textarea>
    <input type="submit" value="Query" />
</form>

