<h1>Search by</h1>
<style type="text/css">
    form.generic label input {
        display: block;
        width: 20em;
    }
</style>
<form action="/addressbook/search" class="generic">
    <p><label>Email <input type="text" name="email" value="<?php print $this->email; ?>" /></label></p>
    <p><label>Nickname <input type="text" name="nickname" value="<?php print $this->nickname; ?>" /></label></p>
    <p><label>Full name <input type="text" name="name" value="<?php print $this->name; ?>" /></label></p>
    <input type="submit" />
</form>

<h2>Or find a specific</h2>
<form action="/addressbook/profile/mbox_sha1sum" class="generic">
    <p><label>Email <input type="text" name="email" value="<?php print $this->email; ?>" /></label></p>
    <input type="submit" />
</form>

<form action="/addressbook/profile/homepage" class="generic">
    <p><label>Homepage <input type="text" name="url" value="<?php print $this->url; ?>" /></label></p>
    <input type="submit" />
</form>


<?php if (!empty($this->result)) { ?>
    <?php print $this->partial('/search/_result_as_table.phtml', $this->result); ?>
<?php } ?>
